Repository mastodon/documentation, pull requests merged in 2023-12, with the labels that each got.

#1335 Improve scaling documentation for Streaming
  content/en/admin/scaling.md
Labels: install-guide

#1329 Proposal for adding minimal documentation for undocumented moderation API (webhook)
  content/en/admin/moderation.md
Labels: API

#1170 Add instructions for seperate sidekiq redis
  content/en/admin/scaling.md
Labels: install-guide, admin

#1268 Role management
  content/en/admin/roles.md
  static/assets/admin-roles-edit-role-ui.png
  static/assets/admin-roles-edit-ui.png
  static/assets/admin-roles-new-ui.png
  static/assets/admin-roles-ui.png
Labels: admin

#1180 Fix the description of `media_attachments` in `StatusEdit`
  content/en/entities/StatusEdit.md
Labels: API

#1210 Fix notification query param LIMIT doc #24684
  content/en/methods/notifications.md
Labels: API

#1354 Add explanation for S3 batch delete variables
  content/en/admin/config.md
  content/zh-cn/admin/config.md
Labels: enhancement

#1359 Branding: switch to purple logo and preferred font.
  README.md
  assets/manrope.scss
  assets/style.scss
  static/brand.svg
  static/favicon.ico
  static/webfonts/manrope/manrope-variable.woff2
Labels: enhancement

#1358 Add troubleshooting instructions for debugging
  content/en/admin/config.md
  content/en/admin/troubleshooting.md
Labels: admin

#1361 Revert "Fix wrong HTML lang attribute on non-English pages (#1247)"
  config.toml
  i18n/en.toml
  i18n/zh-cn.toml
Labels: translation

#1252 Install guide fixes
  content/en/admin/install.md
  content/en/admin/optional/object-storage-proxy.md
  content/zh-cn/admin/install.md
Labels: install-guide

#1340 Update admin install instructions for node 20
  content/en/admin/install.md
Labels: install-guide
