Repository mastodon/documentation, pull requests merged in 2024-03, with the labels that each got.

#1390 Updated the migrating.md document
  content/en/admin/migrating.md
Labels: admin

#1403 Document `ES_CA_FILE`
  content/en/admin/config.md
Labels: enhancement

#1369 Removed unused (not implemented) query parameter.
  content/en/methods/announcements.md
Labels: API
