Repository mastodon/documentation, pull requests merged in 2025-08, with the labels that each got.

#1699 Update README.md
  README.md
Labels: enhancement

#1696 Improvements for the Application entity and methods
  content/en/entities/Application.md
  content/en/methods/apps.md
Labels: API

#1692 Update package names and dependencies in "Installing from source"
  content/en/admin/install.md
Labels: install-guide, admin
